### ISSUE TITLE
GeoIPUseFirstNonPrivateXForwardedForIP On skips all IPv6 addresses

### ISSUE THREAD

**Issue by ache** [maxmind/geoip-api-mod_geoip2#17]
It is because of

```
if (1 != inet_pton(AF_INET, xff_ip, &ipnum)) {
                continue;
}
```

in _get_ip_from_xff(). Please fix .

**Comment by oschwald** [comment]
Thanks for reporting. A pull-request would be welcomed.

**Comment by ache** [comment]
I don't have a machine to test available for a while. Untested simplest code - add before existen (1 != ...) check:
```
#ifdef AF_INET6
struct in6_addr a6;

if (1 == inet_pton(AF_INET6, xff_ip, &a6)) {
    char *found = apr_pstrdup(r->pool, xff_ip);
    return found;
}
#endif
```

**Comment by ache** [comment]
See pull-request #21 (slightly different - use APR configured IPv6 support constants)

**Comment by oschwald** [comment]
Closing as future work is focused on `mod_maxminddb`.
