### ISSUE TITLE
now working on Ubuntu 14.04 Apache 2.4

### ISSUE THREAD

**Issue by ningt** [maxmind/geoip-api-mod_geoip2#18]
$ cat /etc/apache2/mods-enabled/geoip.conf 
    <IfModule mod_geoip.c>
      GeoIPEnable On
      GeoIPScanProxyHeaders On
      GeoIPDBFile /usr/share/GeoIP/GeoIP.dat Standard
    </IfModule>

    $ ll /usr/share/GeoIP/
    -rw-r--r--   1 www-data root 15990880 Jun  3 19:42 GeoIP.dat
    -rw-r--r--   1 root     root  3105495 Apr  7  2014 GeoIPv6.dat

I also installed `libgeoip-dev`, but `echo $_SERVER["GEOIP_COUNTRY_CODE"]` always has empty result. Can anyone help?

**Comment by oschwald** [comment]
You might want to try using [getenv()](http://www.php.net/manual/en/function.getenv.php) or [apache_note()](http://php.net/manual/en/function.apache-note.php). However, please direct any further questions on how to use the module to <support@maxmind.com>.
