### ISSUE TITLE
mod_geoip.so for windows

### ISSUE THREAD

**Issue by vespino** [maxmind/geoip-api-mod_geoip2#22]
I'm planning on upgrading my Apache 2.2 to version 2.4. I'm now looking for the right version of mod_geoip to work with Apache 2.4.17 VC14 64bit (running on Windows by the way). Can anybody tell me where to find it?

**Comment by oschwald** [comment]
This module should work fine with Apache 2.4. We don't test compilation of it on Windows, but if it worked with 2.2, it should likely work with 2.4.
