### ISSUE TITLE
Client denied by server configuration and still works

### ISSUE THREAD

**Issue by vinsiu** [maxmind/geoip-api-mod_geoip2#4]
I am using Apache/2.2.21 on CentOS release 5 (Final), GeoIP-1.5.0 and have compiled mod_geoip_1.2.8.

Now when I put in httpd.conf:

<IfModule mod_geoip.c>
  GeoIPEnable Off
  GeoIPEnableUTF8 On
  GeoIPOutput Env
  GeoIPDBFile /opt/local/geoip/share/GeoIP/GeoIP.dat Standard
</IfModule>

<Location /administrator>
  GeoIPEnable On
  SetEnvIf GEOIP_COUNTRY_CODE PL AllowCountry
  Order deny,allow
  Deny from all
  Allow from env=AllowCountry
</Location>

the server allows IP from Poland, but still writes 'client denied by server configuration' message in the error.log. IPs outside Poland get the same message, but additionally they get 403 error in access.log. IPS from Poland still can see the website, get no 403 error as expected, but the 'client denied' message resides in error.log.

Please could you tell me what can cause the message appear in the logs?

PS If it matters I am using fastcgi_module configured like so:
LoadModule fastcgi_module modules/mod_fastcgi.so
  <IfModule mod_fastcgi.c>
    ScriptAlias /fcgi-bin/ "/opt/local/apache-apc/fcgi-bin/"
    FastCGIExternalServer /opt/local/apache-apc/fcgi-bin/php2-cgi-somevhost -host 127.0.0.1:9014 -idle-timeout 60 -pass-header Authorization
    AddHandler php-fastcgi .php
    Action php-fastcgi /fcgi-bin/php2-cgi-somevhost
  </IfModule>

Best regards
Lukasz

**Comment by nithinkolekar** [comment]
If we can to allow few countries to site and used "Order allow,deny" logic then, we have include all remaining country list to deny block. I had tested with https://briansnelson.com/How_to_block_or_allow_countries_using_GeoIP_and_.htaccess#Allow_Countries_using_GeoIP_and_.htaccess with drupal's .htaccess file and there are not other directives other than mod_geoip2.

I tested by commenting those lines and 'client denied by server configuration' is not logged.
